# Configure a Jenkins worker instance
# This has all the requirements to run test jobs,
# but not the Jenkins Java app.

- name: Configure instance(s)
  hosts: jenkins_worker
  sudo: True
  gather_facts: True
  vars:
      COMMON_DATA_DIR: '/var'
      COMMON_LOG_DIR: '/var/log'
  roles:
    - common
    - edxlocal
    - mongo
    - jenkins_worker
